module.exports = {
  apps: [
    {
      name: "rhdreams",
      script: "dist/server.cjs",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "512M",
      env_production: {
        NODE_ENV: "production",
        PORT: "3000",
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || "",
        GEMINI_FREE_API_KEY: process.env.GEMINI_FREE_API_KEY || "",
        GEMINI_PAID_API_KEY: process.env.GEMINI_PAID_API_KEY || "",
        GROQ_API_KEY: process.env.GROQ_API_KEY || "",
        MICROSOFT_CLIENT_ID: process.env.MICROSOFT_CLIENT_ID || "",
        MICROSOFT_TENANT_ID: process.env.MICROSOFT_TENANT_ID || "",
        MICROSOFT_CLIENT_SECRET: process.env.MICROSOFT_CLIENT_SECRET || "",
        MICROSOFT_REDIRECT_URI: process.env.MICROSOFT_REDIRECT_URI || "https://rh.heavenlydreams.com.mx/api/auth/microsoft/callback",
        JWT_SECRET: process.env.JWT_SECRET || "",
        REDIS_URL: process.env.REDIS_URL || "",
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || "",
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || "",
        GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI || "https://rh.heavenlydreams.com.mx/api/auth/google/callback",
        RHDREAMS_ADMIN_USERNAME: process.env.RHDREAMS_ADMIN_USERNAME || "",
        RHDREAMS_ADMIN_EMAIL: process.env.RHDREAMS_ADMIN_EMAIL || "",
        RHDREAMS_ADMIN_PASSWORD_HASH: process.env.RHDREAMS_ADMIN_PASSWORD_HASH || "",
        RHDREAMS_ADMIN_UID: process.env.RHDREAMS_ADMIN_UID || "admin",
        RHDREAMS_ADMIN_ROLE: process.env.RHDREAMS_ADMIN_ROLE || "Admin",
        RECRUITER_AGENT_NAME: process.env.RECRUITER_AGENT_NAME || "Gissell Arenas",
        DEFAULT_AGENT_PERSONAL_NAME: process.env.DEFAULT_AGENT_PERSONAL_NAME || "Gissell Arenas",
      },
      error_file: "logs/pm2-error.log",
      out_file: "logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      kill_timeout: 5000,
      listen_timeout: 10000,
      // Graceful reload — wait for in-flight requests to finish
      wait_ready: true,
      shutdown_with_message: true,
    },
  ],
};
