name: rhdreamsapp2026
services:
  - name: web
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    build_command: npm run build
    run_command: npm run start
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "3000"
        scope: RUN_AND_BUILD_TIME
